const MessageActions = {
  
  FETCH_ALL_USERS_BY_USERID: "FETCH_ALL_USERS_BY_USERID",
  FETCH_ALL_USERS_BY_USERID_SUCCESS: "FETCH_ALL_USERS_BY_USERID_SUCCESS",

  FETCH_HISTORY_MESSAGE: "FETCH_HISTORY_MESSAGE",
  FETCH_HISTORY_MESSAGE_SUCCESS: "FETCH_HISTORY_MESSAGE_SUCCESS",

};
export default MessageActions;
