const ReportFeedbackActions = {
  REPORT_FEEDBACK: "REPORT_FEEDBACK",
  REPORT_FEEDBACK_SUCCESS: "REPORT_FEEDBACK_SUCCESS",
  FETCH_REPORTS_BY_USERID: "FETCH_REPORTS_BY_USERID",
  FETCH_REPORTS_BY_USERID_SUCCESS: "FETCH_REPORTS_BY_USERID_SUCCESS",
  DELETE_REPORTED_FEEDBACK: "DELETE_REPORTED_FEEDBACK",
  DELETE_REPORTED_FEEDBACK_SUCCESS: "DELETE_REPORTED_FEEDBACK_SUCCESS",
};

export default ReportFeedbackActions;