const ChatboxActions = {
  ADD_MESSAGE: "ADD_MESSAGE",
  ADD_MESSAGE_SUCCESS: "ADD_MESSAGE_SUCCESS",
  CLEAR_MESSAGES: "CLEAR_MESSAGES",
  CLEAR_MESSAGES_SUCCESS: "CLEAR_MESSAGES_SUCCESS",
};

export default ChatboxActions;