const ReservationActions = {
  FETCH_USER_RESERVATIONS: "FETCH_USER_RESERVATIONS",
  FETCH_USER_RESERVATIONS_SUCCESS: "FETCH_USER_RESERVATIONS_SUCCESS",
  FETCH_RESERVATION_DETAIL: "FETCH_RESERVATION_DETAIL",
  FETCH_RESERVATION_DETAIL_SUCCESS: "FETCH_RESERVATION_DETAIL_SUCCESS",
  UPDATE_RESERVATIONS: "UPDATE_RESERVATIONS",
  UPDATE_RESERVATIONS_SUCCESS: "UPDATE_RESERVATIONS_SUCCESS",
};

export default ReservationActions;
