const FeedbackActions = {
  FETCH_USER_FEEDBACKS: "FETCH_USER_FEEDBACKS",
  FETCH_USER_FEEDBACKS_SUCCESS: "FETCH_USER_FEEDBACKS_SUCCESS",
  UPDATE_FEEDBACK: "UPDATE_FEEDBACK",
  UPDATE_FEEDBACK_SUCCESS: "UPDATE_FEEDBACK_SUCCESS",
  DELETE_FEEDBACK: "DELETE_FEEDBACK",
  DELETE_FEEDBACK_SUCCESS: "DELETE_FEEDBACK_SUCCESS",
  CREATE_FEEDBACK: "CREATE_FEEDBACK",
  CREATE_FEEDBACK_SUCCESS: "CREATE_FEEDBACK_SUCCESS",
  FETCH_FEEDBACK_BY_ID: "FETCH_FEEDBACK_BY_ID",
  FETCH_FEEDBACK_BY_ID_SUCCESS: "FETCH_FEEDBACK_BY_ID_SUCCESS",
};

export default FeedbackActions;