const RoomActions = {
  
 
  FETCH_ROOM:"FETCH_ROOM",
  FETCH_ROOM_SUCCESS:"FETCH_ROOM_SUCCESS",
  FETCH_ROOM_DETAIL:"FETCH_ROOM_DETAIL",
  FETCH_ROOM_DETAIL_SUCCESS:"FETCH_ROOM_DETAIL_SUCCESS",
};
export default RoomActions;
